[{"exception": "exception", "inner": [{"provider": {"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "394"}, "caller": {"package": "org.eclipse.cft.server.core.internal.client", "class": "ApplicationOperation", "method": "doApplicationOperation", "filename": "ApplicationOperation", "line": "104"}}, {"provider": {"package": "org.eclipse.cft.server.core.internal.client", "class": "AbstractPublishApplicationOperation", "method": "run", "filename": "AbstractPublishApplicationOperation", "line": "90"}, "caller": {"package": "org.eclipse.cft.server.ui.internal.actions", "class": "PushModuleCommand$1", "method": "run", "filename": "PushModuleCommand", "line": "79"}}], "outer_pre": [], "outer_suf": [], "all": [{"provider": {"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "394"}, "caller": {"package": "org.eclipse.cft.server.core.internal.client", "class": "ApplicationOperation", "method": "doApplicationOperation", "filename": "ApplicationOperation", "line": "104"}}]}]