[{"exception": "error", "inner": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "53"}, "caller": {"package": "webservice.echo", "class": "EchoServiceTest$tempCallbackN1000C", "method": "receiveErrorhello", "filename": "EchoServiceTest", "line": "65"}}], "outer_pre": [], "outer_suf": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "53"}, "caller": {"package": "webservice.echo", "class": "EchoServiceTest$tempCallbackN1000C", "method": "receiveErrorhello", "filename": "EchoServiceTest", "line": "65"}}], "all": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "53"}, "caller": {"package": "webservice.echo", "class": "EchoServiceTest$tempCallbackN1000C", "method": "receiveErrorhello", "filename": "EchoServiceTest", "line": "65"}}]}]