[{"exception": "javax.websocket.DeploymentException", "inner": [{"provider": {"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "320"}, "caller": {"package": "org.eclipse.cft.server.core.internal.client", "class": "BaseClientRequest", "method": "getErrorOnLastFailedAttempt", "filename": "BaseClientRequest", "line": "176"}}, {"provider": {"package": "org.eclipse.cft.server.core.internal.client", "class": "CloudFoundryServerBehaviour", "method": "addApplicationLogListener", "filename": "CloudFoundryServerBehaviour", "line": "845"}, "caller": {"package": "org.eclipse.cft.server.ui.internal.console", "class": "ApplicationLogConsoleStream", "method": "initialiseStream", "filename": "ApplicationLogConsoleStream", "line": "106"}}, {"provider": {"package": "org.eclipse.cft.server.ui.internal.console", "class": "ApplicationLogConsoleManager", "method": "startConsole", "filename": "ApplicationLogConsoleManager", "line": "91"}, "caller": {"package": "org.eclipse.cft.server.ui.internal", "class": "CloudFoundryUiCallback", "method": "startApplicationConsole", "filename": "CloudFoundryUiCallback", "line": "91"}}, {"provider": {"package": "org.eclipse.cft.server.ui.internal", "class": "CloudFoundryUiCallback", "method": "startApplicationConsole", "filename": "CloudFoundryUiCallback", "line": "91"}, "caller": {"package": "org.eclipse.cft.server.core.internal.client", "class": "RestartOperation", "method": "startAndTrackApplication", "filename": "RestartOperation", "line": "104"}}, {"provider": {"package": "org.eclipse.cft.server.core.internal.client", "class": "CloudFoundryServerBehaviour", "method": "publishModule", "filename": "CloudFoundryServerBehaviour", "line": "1390"}, "caller": {"package": "org.eclipse.wst.server.core.model", "class": "ServerBehaviourDelegate", "method": "publishModule", "filename": "ServerBehaviourDelegate", "line": "1091"}}], "outer_pre": [], "outer_suf": [], "all": [{"provider": {"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "320"}, "caller": {"package": "org.eclipse.cft.server.core.internal.client", "class": "BaseClientRequest", "method": "getErrorOnLastFailedAttempt", "filename": "BaseClientRequest", "line": "176"}}]}, {"exception": "org.cloudfoundry.client.lib.CloudOperationException", "inner": [{"provider": {"package": "org.cloudfoundry.client.lib.rest", "class": "CloudControllerClientImpl", "method": "streamLogs", "filename": "CloudControllerClientImpl", "line": "254"}, "caller": {"package": "org.cloudfoundry.client.lib", "class": "CloudFoundryClient", "method": "streamLogs", "filename": "CloudFoundryClient", "line": "376"}}], "outer_pre": [], "outer_suf": [], "all": []}, {"exception": "javax.websocket.DeploymentException", "inner": [{"provider": {"package": "org.apache.tomcat.websocket", "class": "WsWebSocketContainer", "method": "connectToServer", "filename": "WsWebSocketContainer", "line": "374"}, "caller": {"package": "org.cloudfoundry.client.lib.rest", "class": "LoggregatorClient", "method": "connectToLoggregator", "filename": "LoggregatorClient", "line": "64"}}], "outer_pre": [], "outer_suf": [{"provider": {"package": "org.apache.tomcat.websocket", "class": "WsWebSocketContainer", "method": "connectToServer", "filename": "WsWebSocketContainer", "line": "374"}, "caller": {"package": "org.cloudfoundry.client.lib.rest", "class": "LoggregatorClient", "method": "connectToLoggregator", "filename": "LoggregatorClient", "line": "64"}}], "all": [{"provider": {"package": "org.apache.tomcat.websocket", "class": "WsWebSocketContainer", "method": "connectToServer", "filename": "WsWebSocketContainer", "line": "374"}, "caller": {"package": "org.cloudfoundry.client.lib.rest", "class": "LoggregatorClient", "method": "connectToLoggregator", "filename": "LoggregatorClient", "line": "64"}}]}]